#!/bin/sh

case "$1" in
    pre)
      /home/kodi/.kodi/addons/service.tvh.manager/resources/lib/rtc_wakeup.sh
    ;;
    post)
      /usr/bin/ir-keytable --write=/etc/rc_keymaps/rc6_mce --device=/dev/input/mceremote &
    ;;
esac

exit 0

