#!/bin/sh

# Suspend script for PCTV stick. Should be put in /etc/pm/sleep.d/

case "$1" in
  suspend|hibernate)
    if system is-active tvheadend.service; then
      systemctl stop tvheadend.service
#      sleep 2

      rmmod em28xx_rc
      rmmod em28xx_dvb
      rmmod em28xx
      rmmod si2157
      rmmod si2168
    fi
    ;;

  resume|thaw)
    if systemctl is-enabled tvheadend.service; then
      modprobe si2157
      modprobe si2168
      modprobe em28xx
#      sleep 2

      systemctl start tvheadend.service
    fi
    ;;
esac

exit 0

